# Generated by Django 4.2.16 on 2025-11-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_assigned_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complete_requested",
            field=models.BooleanField(default=False),
        ),
    ]
