# Generated by Django 4.2.16 on 2025-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_task_complete_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reason_for_reject",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
